### ISSUE TITLE
How to integrate flutter test and build to this workflow?

### ISSUE THREAD

**Issue by aridgupta** [nrwl/ci#23]
I have a flutter app and a nodejs app inside the repo. But github actions fails every time with an error ```Flutter command not found.```. How do I integrate flutter build tools into this workflow?

**Comment by meeroslav** [comment]
Hi @aridgupta,

I do not have much experience with Flutter, but I would assume there is something you need to install first.
In order to do this, you can leverage the `install-commands` to provide your own command set for installing dependencies.

Let me know if this doesn't work or you have further questions.

**Comment by meeroslav** [comment]
Closing as stale
