### ISSUE TITLE
Add caching node_modules option

### ISSUE THREAD

**Issue by yizumi1012xxx** [nrwl/ci#59]
Feature request.
As dependencies increase in monorepo, yarn commands tend to get longer.
The install time can be shortened by caching the `node_modules`.
Is this worth considering?

**Comment by meeroslav** [comment]
It makes sense, and we do this for our nightly runs, for example. We cache them per run since we run 120 different combinations. Caching `node_modules` in between the runs is not recommended, as a broken installation can get you into a locked state.

The purpose of this reusable workflow is to accommodate the majority of folks so this won't be implemented here. But feel free to create your own workflow where you have then more control over specific segments. I will update docs soon to show how to use your own workflow.
